### ISSUE TITLE
Ant

### ISSUE THREAD

**Issue by pavel-ovsiannikov** [dim3n21/news-app#4]
Посмотри в сторону [Ant](https://ant.design/docs/react/introduce). Возможно он тебе больше понравится с точки зрения визуальщины. Это не значит что я против Bootstrap, просто чтобы ты знал что есть достойные альтернативы.

**Comment by dim3n21** [comment]
Крутая штука. Гораздо больше возможностей чем у React-Bootstrap. Я поменял лоудер на спин из анта. И сделал страницу /checkant с реакт-компонентом CheckAnt, где поигрался с ант-компонентами. Там грязный код, без styled-components, но я просто присматривался, какие функции есть.

**Comment by pavel-ovsiannikov** [comment]
Только обрати внимание, есть и косяки, например, Navbar при адаптивности порождает горизонтальный скролл из-за чего прила на мелких экранах (например, iphone se) смотрится убого. В остальном - да, он красив и юзабелен.
